# Generated by Django 5.1.4 on 2024-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('technologies', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', 'title'],
            },
        ),
    ]
