# Generated by Django 5.1.4 on 2024-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_alter_casestudy_challenge_alter_casestudy_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='client_industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
