# Generated by Django 5.1.4 on 2024-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0003_casestudy_client_industry_casestudy_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
